import type { Topic } from '@/types/content'

const topic: Topic = {
  id: '01-panorama',
  title: 'Why We Need a Market: From Chaos to the Exchange',
  type: 'lecture',
  estimatedMinutes: 25,
  sections: [
    {
      id: 'no-market',
      title: 'What Happens When We Don’t Have a Market?',
      body: `This is a course about **commodity trading** — so start from the opposite end: *imagine there is no market at all.*\n\nPicture the coffee chain without an exchange: **millions of growers**, thousands of exporters and roasters, scattered across continents, each negotiating **bilaterally, in the dark**. Two structural problems appear immediately — and everything in this course exists to solve them:\n\n1. **No reference price.** Every deal is private. Nobody knows what the "right" price is — not the farmer selling his crop, not the roaster committing to next year's blends. Every negotiation starts from zero, and the better-informed side wins. Information *is* the margin.\n2. **No protection in advance.** Whatever you will need to buy — or have to sell — next season, you will pay (or receive) *whatever the price happens to be then*. There is no instrument to lock a price today for a delivery in six months. Price risk sits with whoever physically holds, or has promised, the goods — and it cannot be moved.\n\nRun the thought experiment below: slide the number of participants and toggle between the **bilateral world** — where every producer must find and price against every buyer — and a world with **one central marketplace**. The negotiation burden goes from quadratic to linear; the price goes from private to public.`,
      visual: 'network-explosion',
    },
    {
      id: 'no-exchange',
      title: 'Markets That Turned Crazy: Olive Oil, Rice, Pepper & Onions',
      body: `These are not thought experiments. Look at the real markets that **never got a liquid futures contract** — and what happened when their fundamentals moved.\n\n**Olive oil, 2022–24.** Spanish drought sent extra-virgin from ~€2,000/t to nearly €9,000/t and back down. Every importer and bottler simply **ate the move** — no hedge to lay it off, no transparent reference to negotiate against, no buyer of last resort for stuck stock.\n\nAnd here is the uncomfortable part: **even the best olive-oil buyer in Europe could not have done much.** The two "physical" defences both fail:\n\n- **You cannot stock your way out.** A bottler's tanks hold perhaps **one month of supply** — storage is expensive, oil degrades, and capital is tied up. Seeing the drought coming does not help if you physically cannot hold more than four weeks of it.\n- **You can buy forward… into massive counterparty risk.** Contract future shipments at today's price, and when the market doubles your supplier faces a choice: honour a contract that now ruins him, or **walk away**. Many walked. An unsecured bilateral promise is only as good as the counterparty's solvency — and precisely when you need it most, it defaults. (Remember this: the *clearing house* exists to kill exactly this risk.)\n\n**Rice, 2008.** No liquid global hedge, thin visibility on stocks. When exporters (India, Vietnam) restricted exports, panic did the pricing: world rice **tripled in months**, importing nations hoarded, and the spike fed itself — then collapsed.\n\n**Vietnamese pepper, 2015–19.** Farmers planted at $10,000/t with no forward market to signal or lock future prices; three harvests later pepper traded under $2,000/t and orchards were ripped out. A futures curve would have *shown* the wall of supply coming — and let growers sell it forward.\n\n**US onions — the natural experiment.** Onions HAD a futures market, until a 1958 law (the *Onion Futures Act*, still in force) banned it. The result, studied ever since: onion prices became **more** volatile than before the ban and more volatile than comparable vegetables. The farmers who lobbied for the ban got wilder prices, not calmer ones.\n\nThe volatility in these markets is not worse than coffee's; the difference is that **coffee traders can do something about it**.`,
      visual: 'unhedgeable-markets',
    },
    {
      id: 'cbot-history',
      title: '1848: Chicago Invents the Answer',
      body: `The solution was not designed by economists — it was improvised by grain merchants who lived the no-market world daily.\n\n**Chicago, 1840s.** Every autumn, wagons of Midwest grain flooded into a city with too little storage. Prices collapsed at harvest — there are accounts of unsold grain **dumped into Lake Michigan** — then soared by spring when stocks ran out. Farmers had no idea what price they would get before making the journey; millers had no way to secure winter supply. Both problems of Section 1, at full scale.\n\n**1848 — the reference price.** Eighty-two merchants founded the **Chicago Board of Trade (CBOT)**: one trading floor where grain deals were struck *in public*. A quoted, visible price replaced the private haggle — the **reference price** was born, and the telegraph spread it across the country within years.\n\n**“To-arrive” contracts — protection in advance.** On that floor, buyers and sellers began agreeing prices today for grain **delivered later** ("to arrive"). The farmer locked his sale before the harvest glut; the miller locked his winter supply in autumn. In **1865** the CBOT standardised these promises — fixed grades, fixed lot sizes, fixed delivery months — and required both sides to post **margin**. The forward promise became a **futures contract**: tradeable, transferable, no longer dependent on trusting a stranger.\n\n**Clearing — killing counterparty risk.** Margin evolved into a full **clearing house** (guaranteeing every CBOT trade from 1925): the exchange itself steps between buyer and seller, so the olive-oil failure — *your supplier walks away exactly when the contract is worth most* — structurally cannot happen.\n\nEvery futures exchange since — CME, ICE, LME — is the same three-part invention: **a public price, a way to fix it in advance, and a guarantee that the promise holds.**`,
      visual: 'cbot-timeline',
    },
    {
      id: 'why-market',
      title: 'Why Do We Need a Market?',
      body: `Now return to coffee — a market that **has** the machinery olive oil lacks — and state the answer properly.\n\nA **futures exchange** solves the no-market problems all at once. It is a single, **centrally-cleared marketplace** where the whole supply chain can transfer price risk and read **one transparent price** — and, because the contract is physically deliverable, it acts as the **buyer and seller of last resort** for standard-spec coffee.\n\nThe three functions feed each other through **liquidity**: deep participation makes the price meaningful (**price discovery**), a meaningful price makes hedging work (**risk management**), and guaranteed delivery anchors it all to physical reality.\n\nFor coffee, that marketplace is the **Intercontinental Exchange (ICE)** — a Fortune 500 exchange operator (NYSE: ICE, also owner of the New York Stock Exchange) that runs the benchmark **Arabica (New York)** and **Robusta (London)** futures used to price and hedge physical coffee worldwide. The scale is striking: ICE reports the equivalent of roughly **400 million tonnes** traded across its coffee markets in a single year — more than **2,000 times** the world's physical crop.`,
      visual: 'exchange-functions',
    },
  ],
}

export default topic
